#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V  

bspc config border_width        2 
bspc config window_gap          0
bspc config focused_border_color "#43a047"

# BSPWM Config Polybar
bspc config top_padding                   30
bspc config bottom_padding                30
bspc config left_padding                  0
bspc config right_padding                 0
# END BSPWM

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=fl2ating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill $HOME/.config/bspwm/bg.jpg

$HOME/.config/polybar/launch.sh
